---
- hosts: centos7

  vars:
    - directorio: ~/ProyectoCC
  
  tasks: 
    - name: Instala git
      become: yes
      yum: pkg=git state=present
    
    - name: Instala curl 
      become: yes
      yum: pkg=curl state=latest
      
    - name: Agrega PPA Node.js
      become: yes
      shell: curl -sL https://rpm.nodesource.com/setup_11.x | bash -
      args: 
        warn: no
      
    - name: Instala Node.js
      become: yes
      yum: pkg=nodejs state=latest
    
    - name: Instala forever
      become: yes
      npm: name=forever global=yes state=present
        
    - name: Instala MongoDB
      become: yes
      yum:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Inicia MongoDB
      become: yes
      service:
        name: mongod
        state: started
      
    - name: Descarga el proyecto del repositorio
      git: 
        repo: https://github.com/MarAl15/ProyectoCC.git
        dest: "{{ directorio }}"
        force: yes
        
    - name: Instala dependencias basadas en package.json
      npm:
        path: "{{ directorio }}"
        
