---
- hosts: debian9

  vars:
    - directorio: ~/ProyectoCC
  
  tasks: 
    - name: Instala git
      become: yes
      apt: pkg=git state=present
    
    - name: Instala curl 
      become: yes
      apt: pkg=curl state=latest
      
    - name: Agrega PPA Node.js
      become: yes
      shell: curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
      args: 
        warn: no
      
    - name: Instala Node.js
      become: yes
      apt: pkg=nodejs state=latest
    
    - name: Instala forever
      become: yes
      npm: name=forever global=yes state=present
    
    - name: Importa la clave pública MongoDB
      become: yes
      shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4

    - name: Añade repositorio MongoDB
      become: yes
      shell: echo "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
        
    - name: Instala MongoDB
      become: yes
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Inicia MongoDB
      become: yes
      service:
        name: mongod
        state: started
      
    - name: Descarga el proyecto del repositorio
      git: 
        repo: https://github.com/MarAl15/ProyectoCC.git
        dest: "{{ directorio }}"
        force: yes
        
    - name: Instala dependencias basadas en package.json
      npm:
        path: "{{ directorio }}"
        
