---
- hosts: db

  vars:
    - directorio: ~/ProyectoCC
  
  tasks:     
    - name: Importa la clave pública MongoDB
      become: yes
      shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4

    - name: Añade repositorio MongoDB
      become: yes
      shell: echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list

    - name: Instala MongoDB
      become: yes
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Inicia MongoDB
      become: yes
      service:
        name: mongod
        state: started        
