Vagrant.configure('2') do |config|
	config.vm.box = 'azure'

	# Clave ssh
	config.ssh.private_key_path = '~/.ssh/id_rsa'
		
	config.vm.define "app" do |app|	
		app.vm.provider :azure do |azure, override|
			# Cuenta de Azure
			azure.tenant_id = ENV['AZURE_TENANT_ID']
			azure.client_id = ENV['AZURE_CLIENT_ID']
			azure.client_secret = ENV['AZURE_CLIENT_SECRET']
			# Subcripción de Azure
			azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

			# Nombre de la MV
			azure.vm_name = 'calendar'
			# Nombre del grupo de recursos
			azure.resource_group_name = 'CCGroupH5'
			# Nombre de usuario
			azure.admin_username ='usuario'
			
			# Localización de la MV
			azure.location =  'francecentral'
			
			# Imagen a instalar en la MV
			azure.vm_image_urn = 'Canonical:UbuntuServer:18.04-LTS:18.04.201901140'	
			
			# Tamaño
			azure.vm_size = 'Standard_B1s'
			
			# Puertos a abrir
			azure.tcp_endpoints = [80,27017]
			
			# Red virtual
			azure.virtual_network_name = "redH5"
		end
		
		app.vm.provision "ansible" do |ansible|
			ansible.playbook = "recetaApp.yml"
			ansible.host_vars = {
			  "app" => {"ansible_ssh_user" => "usuario"}
			}
		end
	end

	config.vm.define "db" do |db|
		db.vm.provider :azure do |azure, override|
			# Cuenta de Azure
			azure.tenant_id = ENV['AZURE_TENANT_ID']
			azure.client_id = ENV['AZURE_CLIENT_ID']
			azure.client_secret = ENV['AZURE_CLIENT_SECRET']
			# Subcripción de Azure
			azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

			# Nombre de la MV
			azure.vm_name = 'database'
			# Nombre del grupo de recursos
			azure.resource_group_name = 'CCGroupH5'
			# Nombre de usuario
			azure.admin_username ='usuario'
			
			# Localización de la MV
			azure.location =  'francecentral'
			
			# Imagen a instalar en la MV
			azure.vm_image_urn = 'Canonical:UbuntuServer:18.04-LTS:18.04.201901140'

			# Tamaño
			azure.vm_size = 'Standard_B1s'
			
			# Puertos a abrir
			azure.tcp_endpoints = 27017
			
			# Red virtual
			azure.virtual_network_name = "redH5"
		end
		
		db.vm.provision "ansible" do |ansible|
			ansible.playbook = "recetaDB.yml"
			
			ansible.host_vars = {
			  "app" => {"ansible_ssh_user" => "usuario"}
			}
		end
	end
end
